# Generated by Django 5.1.2 on 2024-11-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretsanta", "0002_exclusions_drawnname_wishlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="exclusions",
            name="selected",
            field=models.ManyToManyField(
                related_name="excluded", to="secretsanta.participant"
            ),
        ),
    ]
