# Generated by Django 5.1.2 on 2024-11-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretsanta", "0003_alter_participant_options_alter_exclusions_selected"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Processed"),
                ),
                ("from_number", models.CharField(max_length=20, verbose_name="From")),
                ("to_number", models.CharField(max_length=20, verbose_name="From")),
                (
                    "is_received",
                    models.BooleanField(default=True, verbose_name="Is Received"),
                ),
                ("body", models.TextField()),
                ("smssid", models.CharField(max_length=200, verbose_name="MessageSID")),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="secretsanta.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-processed_datetime"],
            },
        ),
    ]
