# Generated by Django 5.1.2 on 2024-11-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0005_drawnname_drawn_sent_drawnname_intro_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawnname',
            name='recipient_wishlist_sent',
            field=models.BooleanField(default=False),
        ),
    ]
