# Generated by Django 5.1.2 on 2024-11-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0006_alter_drawnname_recipient_wishlist_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
