# Generated by Django 5.1.2 on 2024-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0007_wishlist_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
