# Generated by Django 5.1.2 on 2024-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0008_wishlist_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawnname',
            old_name='drawn_sent',
            new_name='drawn_1_sent',
        ),
        migrations.AddField(
            model_name='drawnname',
            name='drawn_2_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawnname',
            name='drawn_3_sent',
            field=models.BooleanField(default=False),
        ),
    ]
