image: docker:18.09.7-dind

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  DOCKER_DRIVER: overlay2
  # DOCKER_HOST: tcp://docker:2375
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - ${TF_ROOT}/.terraform
    - .cache/pip

services:
  - docker:18.09.7-dind

stages:
  - build
  - prepare
  - deploy
  - destroy

#########################################################
## Docker Bits
#########################################################
docker_build:
  image: docker:18.09.7-dind
  stage: build
  variables:
    MAIN_TAG: latest
    COMPONENT: snowflake_secret_santa
    BUILD_PATH: "./"
    DOCKERFILE: ""
  script:
    - apk add --no-cache curl jq
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

    - echo "Building GitLab image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/$COMPONENT:$MAIN_TAG || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/$COMPONENT:$MAIN_TAG -t $CI_REGISTRY_IMAGE/$COMPONENT:$MAIN_TAG $DOCKERFILE $BUILD_PATH
    - docker push $CI_REGISTRY_IMAGE/$COMPONENT:$MAIN_TAG